### PR TITLE
Handle the ZIP+4/9-digit (delivery route) zipcodes

### PR DESCRIPTION
**Pull request by seanpianka**
Rather than throwing a `TypeError` exception for [ZIP+4/9-digit zipcodes](https://smartystreets.com/articles/zip-4-code), strip the delivery route code and use the initial 5 digits and return the expected `Zip` object.

Old behavior:
```python
>>> import zipcode
>>> zipcode.isequal("06469-1145")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../zipcode/__init__.py", line 113, in isequal
    _validate(zipcode)
  File "/.../zipcode/__init__.py", line 102, in _validate
    int(zipcode) # This could throw an error if zip is not made of numbers
ValueError: invalid literal for int() with base 10: '06469-1145'
```

New behavior:
```python
>>> import zipcode
>>> zipcode.isequal("06469-1145")
<Zip: 06469>
>>> zipcode.isequal("06469-1145").state
'CT'
```

### CODE REVIEW

**Comment by buckmaxwell** [comment]
@seanpianka, I can see the advantage here but am not sure if this would be the expected behaviour.  This package is going to get a major update soon.  If you'd like to be part of that effort let me know.

**Comment by seanpianka** [comment]
Yeah, I'd appreciate being included in that since I use this package for a project of mine.

As to the behavior... there are two types of zipcodes: 

- 5-digit zipcodes which indicate the destination post office or delivery area
- 9-digit zipcodes where the additional four are called the ZIP+4 Code and represent a specific delivery route

The delivery route (last 4 digits) does not modify the actual location that the zipcode represents, merely which route the delivery driver should drive when delivering a package to the (assumed) specific address.

Given that the first 5 digits represent the location, but both are valid and standardized zipcode formats, the behavior I've implemented would be the expected behavior (or, it was by me!).

**Comment by buckmaxwell** [comment]
Sean, we are beginning the slack channel for the zipcode project.  Can you
send me a good email?  Send to maxbuckdeveloper@gmail.com

Max

**Comment by buckmaxwell** [comment]
closing due to inactivity.

**Pull request closed without merging**
